### ISSUE TITLE
Planned updates?

### ISSUE THREAD

**Issue by mattpilott** [ClaytonFarr/sveltekit-netlify-stripe-fauna-example#4]
Hi @ClaytonFarr i've looked into this repo a few times and think you've done a great job showcasing what a lot of devs find very difficult. I'm wondering if you plan to update this at all with the latest package versions and solutions to some of the items you didn't get around to (security and so forth)

Thanks!

**Comment by ClaytonFarr** [comment]
Hi @mattpilott, thanks for the kind words. It's great to hear this has been useful.

I would like to update things here back to a working state with the latest versions of SvelteKit, etc. I don't think I'll have time to do this until later this summer, at best. 

In the course of doing this, I would like to fix a few things and implement any new security or usability features SK may have sorted out in the mean time (e.g [CSRF](https://github.com/sveltejs/kit/issues/72), [progressive forms](https://github.com/sveltejs/kit/issues/3533))

**Comment by ClaytonFarr** [comment]
A newer version of this idea (built with SvelteKit2, Svelte5, and SQLite) is available here, for anyone in need of something similar – https://github.com/ClaytonFarr/justship
